on:
  push:
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npx -y .scripts/update.mts
      - run: |-
          git diff
          git config --global user.email "deniz@deniz.blue"
          git config --global user.name "deniz-blue"
          git add -A
          git commit -m "[skip ci] Auto update README" || exit 0
          git push
      
